name: tda
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=21.2.1
  - joblib=1.1.1
  - scikit-learn=1.2.0
  - ipyparallel=6.3.0
  - gudhi=3.4.1
  - numpy=1.23.5
  - pandas=1.5.2
  - statsmodels=0.13.5
  - bokeh=2.4.2
  - mpi4py=3.1.4
  - jupyter-server-proxy
  - conda-forge::glmnet
  - conda-forge::dask-mpi
  - conda-forge::dask-jobqueue

